# Generated by Django 5.0.6 on 2024-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_user_details_extend_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='displaydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=100, null=True)),
                ('title', models.TextField()),
            ],
        ),
    ]
