# Generated by Django 5.0.6 on 2024-07-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_displaydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='displaydata',
            new_name='displaydata1',
        ),
    ]
